# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Productos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SCLAlertView'
  pod 'MBProgressHUD'

  target 'ProductosTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

  target 'ProductosUITests' do
    # Pods for testing
  end

end
